services:
  TweedeGolf\PrometheusClient\CollectorRegistry:
    class: TweedeGolf\PrometheusClient\CollectorRegistry
    arguments:
      - '@TweedeGolf\PrometheusClient\Storage\RedisAdapter'
      - false
      - false

  TweedeGolf\PrometheusClient\Storage\RedisAdapter:
    class: TweedeGolf\PrometheusClient\Storage\RedisAdapter
    arguments:
      - '@redis'
      - '%metric_redis_prefix%'

  #################
  #               #
  #  Tag section  #
  #               #
  #################

  #########################
  #                       #
  #  Weather tag section  #
  #                       #
  #########################

  tweede_golf.prometheus_client.collector.app_weather_temperature:
    class: TweedeGolf\PrometheusClient\Collector\Histogram
    factory: TweedeGolf\PrometheusClient\CollectorRegistry:createHistogram
    arguments:
      - 'app_weather_temperature'
      - ['env', 'weather', 'device_name']
      - 'Temperature'
    tags: [tweede_golf_prometheus.collector]

  tweede_golf.prometheus_client.collector.app_weather_humility:
    class: TweedeGolf\PrometheusClient\Collector\Histogram
    factory: TweedeGolf\PrometheusClient\CollectorRegistry:createHistogram
    arguments:
      - 'app_weather_humility'
      - ['env', 'weather', 'device_name']
      - 'Humility'
    tags: [tweede_golf_prometheus.collector]

  tweede_golf.prometheus_client.collector.app_weather_rain_fall:
    class: TweedeGolf\PrometheusClient\Collector\Histogram
    factory: TweedeGolf\PrometheusClient\CollectorRegistry:createHistogram
    arguments:
      - 'app_weather_rain_fall'
      - ['env', 'weather', 'device_name']
      - 'Rain fall'
    tags: [tweede_golf_prometheus.collector]

  tweede_golf.prometheus_client.collector.app_weather_wind_speed:
    class: TweedeGolf\PrometheusClient\Collector\Histogram
    factory: TweedeGolf\PrometheusClient\CollectorRegistry:createHistogram
    arguments:
      - 'app_weather_wind_speed'
      - ['env', 'weather', 'device_name']
      - 'Wind speed'
    tags: [tweede_golf_prometheus.collector]

  tweede_golf.prometheus_client.collector.app_weather_wind_direction:
    class: TweedeGolf\PrometheusClient\Collector\Histogram
    factory: TweedeGolf\PrometheusClient\CollectorRegistry:createHistogram
    arguments:
      - 'app_weather_wind_direction'
      - ['env', 'weather', 'device_name']
      - 'Wind direction'
    tags: [tweede_golf_prometheus.collector]
