{
 "title": "Weather",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Wind speed (m/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_weather_wind_speed_sum) by (device_name)/sum(app_weather_wind_speed_count) by (device_name)",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Wind direction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_weather_wind_direction_sum) by (device_name)/sum(app_weather_wind_direction_count) by (device_name)",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Rain fall (mm/m^2)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_weather_rain_fall_sum) by (device_name)/sum(app_weather_rain_fall_count) by (device_name)",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Humility",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_weather_humility_sum) by (device_name)/sum(app_weather_humility_count) by (device_name) ",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_weather_temperature_sum) by (device_name)/sum(app_weather_temperature_count) by (device_name)  ",
     "legendFormat": "{{device_name}}"
    }
   ]
  }
 ]
}